#!/usr/bin/env bash

CACHE_PATH="${HOME}/.cache/afd.txt"
CONFIG_PATH="${HOME}/.config/afd.cfg"

BASE_URL="https://aviationweather.gov/api/data"

afd() {
	local default="kpah"
	local id="${1:-$default}"
	local url="${BASE_URL}/fcstdisc?cwa=${id}&type=af"
	curl -s "$url" | bat
}

metar() {
	local id="${1:-$default}"
	local url="${BASE_URL}/metar?ids=${id}&format=raw"
	curl -s "$url" && echo
}

taf() {
	local id="${1:-$default}"
	local url="${BASE_URL}/taf?ids=${id}&format=raw"
	curl -s "$url" && echo
}

main() {
	case "$1" in
		af)
			echo "Implement area forecast (short)"
			;;
		afd) # area forecast discussion (full)
			afd ${2}
			;;
		atis)
			echo "Implement ATIS"
			;;
		metar)
			metar ${2}
			;;
		taf)
			taf ${2}
			;;
		.)
			echo "Default weather case. METAR/ATIS, TAF, AF"
			;;
		*)
			echo "Usage: $0 {af|afd|atis|metar|taf|.} [station]"
			;;
	esac
}

main ${@}
